export const BOUNTIES_DATA = [
  { 
    id: "1", 
    title: "Duolingo Language Chaos Challenge", 
    brand: "DuoLearn", 
    logo: "https://logo.clearbit.com/duolingo.com",
    payout: "15", 
    payoutSub: "per 1,000 qualified views",
    platforms: ["tiktok", "instagram"], 
    budget: "$50,000", 
    deadline: "Oct 24, 2025",
    timeLeft: "2d left",
    filled: 45,
    badgeText: "Only 2 days left",
    posted: "Posted 3 days ago",
    theme: "from-green-50 to-white",
    description: "DuoLearn (yes, the owl’s cousin) is launching a new language-learning feature, and we need bold, funny, chaotic creators to show how FUN learning a language can be.\n\nYour mission is simple: Make a video so entertaining that people forget they’re learning something.\n\nThink: “Learn Spanish or ELSE.” crying green owl memes, relatable language mistakes, gamified progress addiction, your wild reactions to streak pressure.\n\nMake it fun. Make it chaotic. Make Duo proud.",
    requirements: ["Show the app in first 3s", "Use campaign audio", "Tag @DuoLearn", "Min length: 15s"],
    format: "9:16 Vertical Video"
  },
  { 
    id: "2", 
    title: "Aesthetic 2025 Workspace Setup", 
    brand: "Notion", 
    logo: "https://logo.clearbit.com/notion.so",
    payout: "25", 
    payoutSub: "per 1,000 qualified views",
    platforms: ["youtube"], 
    budget: "$20,000", 
    deadline: "Oct 28, 2025",
    timeLeft: "5d left",
    filled: 72,
    badgeText: "5 days left",
    posted: "Posted 5 hours ago",
    theme: "from-zinc-100 to-white",
    description: "New Year, New System. We want to see your ultimate 2025 life-operating system.\n\nYour mission: Show how you organize your chaotic life into a beautiful, functional dashboard using our new 2025 templates.\n\nThink: Lo-fi study beats, cozy desk setups, satisfying checkbox clicks, and dark mode aesthetic. It needs to be functional, but more importantly, it needs to be BEAUTIFUL.\n\nStop being messy. Start being aesthetic.",
    requirements: ["Show 2025 template", "Dark Mode toggle", "Tag @Notion", "No talking required"],
    format: "YouTube Shorts"
  },
  { 
    id: "3", 
    title: "Coding with AI Superpowers", 
    brand: "Cursor", 
    logo: "https://logo.clearbit.com/cursor.com", 
    payout: "40", 
    payoutSub: "per 1,000 qualified views",
    platforms: ["twitter"], 
    budget: "$10,000", 
    deadline: "Ended",
    timeLeft: "12h left",
    filled: 100,
    badgeText: "SOLD OUT",
    posted: "Posted 1 day ago",
    theme: "from-indigo-50 to-white",
    description: "This bounty is currently CLOSED. The budget has been fully allocated.\n\nCursor is the AI code editor that lets you build software faster. We wanted to see how fast you could build a landing page using our new 'Composer' feature.",
    requirements: ["Campaign Closed", "Budget Exhausted", "Watch for future drops"],
    format: "Twitter / X Video"
  },
  { 
    id: "4", 
    title: "Murder Your Thirst", 
    brand: "Liquid Death", 
    logo: "https://logo.clearbit.com/liquiddeath.com",
    payout: "18", 
    payoutSub: "per 1,000 qualified views",
    platforms: ["instagram", "tiktok"], 
    budget: "$35,000", 
    deadline: "Ended",
    timeLeft: "1w left",
    filled: 100,
    badgeText: "SOLD OUT",
    posted: "Posted 1 week ago",
    theme: "from-red-50 to-white",
    description: "This bounty is currently CLOSED.\n\nWe wanted to see you murder your thirst. The internet responded. The budget is dead.",
    requirements: ["Campaign Closed", "Budget Exhausted"],
    format: "Instagram Reels"
  },
  { 
    id: "5", 
    title: "Latte Art at Home Challenge", 
    brand: "Starbucks", 
    logo: "https://logo.clearbit.com/starbucks.com",
    payout: "30", 
    payoutSub: "per 1,000 qualified views",
    platforms: ["tiktok"], 
    budget: "$75,000", 
    deadline: "Nov 01, 2025",
    timeLeft: "4d left",
    filled: 58,
    badgeText: "Trending",
    posted: "Posted 2 hours ago",
    theme: "from-emerald-50 to-white",
    description: "We want to see your morning ritual. Whether it's a perfect pour or a hilarious fail, show us how you start your day with Starbucks at Home. Make it cozy, make it chaotic, just make it coffee.",
    requirements: ["Must use a Starbucks mug or bag", "Morning vibes aesthetic", "Tag @StarbucksAtHome", "ASMR sounds preferred"],
    format: "TikTok / Reels"
  },
  { 
    id: "6", 
    title: "Glow Up Morning Routine", 
    brand: "Fenty Beauty", 
    logo: "https://logo.clearbit.com/fentybeauty.com",
    payout: "45", 
    payoutSub: "per 1,000 qualified views",
    platforms: ["instagram", "tiktok"], 
    budget: "$120,000", 
    deadline: "Oct 30, 2025",
    timeLeft: "6d left",
    filled: 80,
    badgeText: "High Payout",
    posted: "Posted 1 day ago",
    theme: "from-amber-50 to-white",
    description: "Get ready with us. Show your transformation from 'just woke up' to 'ready to conquer' using Fenty Skin and Beauty products. We want real skin textures and genuine reactions.",
    requirements: ["Before & After transition", "List products in caption", "Tag @FentyBeauty", "Upbeat trending audio"],
    format: "9:16 Vertical Video"
  },
  { 
    id: "7", 
    title: "Show Your Spotify Wrapped", 
    brand: "Spotify", 
    logo: "https://logo.clearbit.com/spotify.com",
    payout: "25", 
    payoutSub: "per 1,000 qualified views",
    platforms: ["tiktok"], 
    budget: "$90,000", 
    deadline: "Dec 01, 2025",
    timeLeft: "8d left",
    filled: 20,
    badgeText: "Seasonal",
    posted: "Posted 4 hours ago",
    theme: "from-green-50 to-white",
    description: "It's that time of year. Expose your music taste. Whether you're proud or embarrassed, share your Top 5 Artists and your Listening Personality. Roast yourself or flex your taste.",
    requirements: ["Green screen effect over your Wrapped", "Commentary on your top artist", "Tag #SpotifyWrapped", "No copyright music (use library)"],
    format: "TikTok / Reels"
  },
  { 
    id: "8", 
    title: "Before & After Writing", 
    brand: "Grammarly", 
    logo: "https://logo.clearbit.com/grammarly.com",
    payout: "18", 
    payoutSub: "per 1,000 qualified views",
    platforms: ["youtube"], 
    budget: "$40,000", 
    deadline: "Nov 15, 2025",
    timeLeft: "10d left",
    filled: 67,
    badgeText: "Easy",
    posted: "Posted 6 hours ago",
    theme: "from-emerald-50 to-white",
    description: "Show a chaotic, typo-filled email draft... and then the magic fix. Demonstrate how Grammarly saves you from sending embarrassing texts to your boss or professor.",
    requirements: ["Screen recording of the 'Fix All' button", "Relatable work/school scenario", "Tag @Grammarly", "Humorous tone"],
    format: "Any Format"
  },
  { 
    id: "9", 
    title: "My Weekend Airbnb Find", 
    brand: "Airbnb", 
    logo: "https://logo.clearbit.com/airbnb.com",
    payout: "55", 
    payoutSub: "per 1,000 qualified views",
    platforms: ["instagram"], 
    budget: "$150,000", 
    deadline: "Nov 10, 2025",
    timeLeft: "1w left",
    filled: 49,
    badgeText: "Travel",
    posted: "Posted 2 days ago",
    theme: "from-rose-50 to-white",
    description: "Found a unique stay? A cabin in the woods? A downtown loft? Give us a 15-second tour of your weekend getaway. Focus on the unique details that make it special.",
    requirements: ["Walkthrough tour style", "Mention the specific 'Category' (e.g. Amazing Pools)", "Tag @Airbnb", "Cozy/Wanderlust vibe"],
    format: "Instagram Reels"
  },
  { 
    id: "10", 
    title: "Train Like an Athlete", 
    brand: "Nike", 
    logo: "https://logo.clearbit.com/nike.com",
    payout: "50", 
    payoutSub: "per 1,000 qualified views",
    platforms: ["youtube"], 
    budget: "$200,000", 
    deadline: "Nov 20, 2025",
    timeLeft: "3w left",
    filled: 28,
    badgeText: "Active",
    posted: "Posted 12 hours ago",
    theme: "from-zinc-100 to-white",
    description: "Just do it. Show us your intense training session, your morning run, or your recovery routine. We want grit, sweat, and determination. Show us what you're working for.",
    requirements: ["Wearing Nike gear visibly", "High energy editing", "Tag @Nike + #JustDoIt", "Motivational voiceover"],
    format: "TikTok / Shorts"
  }
];
